### ISSUE TITLE
Update your code

### ISSUE THREAD

**Issue by Stepandanci** [andreiversilov/WatirProject_AC#3]
1. Read Ruby style guide.
You can install `rubocop` gem for refactor code.

2. Update code structure

Move `Account` class to `account.rb` file and `Transactions` class to `transactions.rb` file.
Separate code logic in `fetch` and `parsing` methods and update code structure.

#### Example code structure:

```ruby
class ExampleBank

  def execute
    connect
    fetch_accounts
    fetch_transactions
    save_result # in JSON file
  end

  def connect
    # here you log in to the bank
  end

  def fetch_accounts
    # fetch html data using nokogiri, take only fragment of html.
    html = Nokogiri::HTML.fragment(browser.div(class: "example").html)
    parse_accounts(html)
  end

  def fetch_transactions
    # go to transactions
    # set date for 2 month
    parse_transactions(account, html)
  end

  def parse_accounts(html)
    # parse accounts here
  end

  def parse_transactions(account, html)
    # parse transactions here
  end
end
```

3. Update data structure

Save all JSON data in a file, I need to check result.
Read again your test task, and check example.
```json
{
  "accounts": [
    {
      "name": "account1",
      "currency": "MDL",
      "balance": 300.22,
      "nature": "account",
      "transactions": [
        {
            "date": "2015-01-15",
            "description": "bought food",
            "amount": -20.31,
            "currency": "MDL",
            "account_name": "account1"
        }
      ]
    }
  ]
}
```
date must be it json format example: "2020-08-20",
balance and amount must be float not string.

## Write tests

You should write a test that checks the data from demo bank.

1. Read about Rspec. It is a framework for test your code.

- https://rspec.info
- https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers

2. Write specs for `parse_accounts` and `parse_transactions`.

3. Take HTML from demo bank and save it in a file (check screenshot).
`html_example = Nokogiri::HTML(File.read('accounts.html'))`

![Снимок](https://user-images.githubusercontent.com/29861352/84526427-f2d8bc80-ace5-11ea-81e2-b36cf686705d.PNG)

4. Call method for parse accounts and send HTML data. `parse_accounts(html_example)`

5. Check the number of accounts and show an example account in a hash format.

Example:
```ruby
it 'check number of accounts and show an example account' do
  html_example = Nokogiri::HTML(File.read('accounts.html'))
  accounts = parse_accounts(html_example) # NOTE: It is my example, not a real code.

  expect(accounts.count).to eq(5)
  expect(accounts.first.to_hash).to eq(
    {
      "name"         => "Demo Everyday Account",
      "currency"     => "USD",
      "balance"      => 1959.90,
      "nature"       => "account",
      "transactions" => []
    }
  )
end
```

6. Do the same for transactions.

Good luck!

**Comment by andreiversilov** [comment]
Hello. I did Stepan's assignment. Everything is done as directed except for
a few points. I wrote the tests differently. Since the page itself changes
periodically. And the numbers and the account also change. But the amount
of transactions and the number of accounts do not change. This is what I
tested. I also rewrote and improved a lot. Now without compromise, all
parsing on Nokogiri.This time I use rubocop completely. Thanks for your
feedback. hhttps://github.com/andreiversilov/WatirProject_AC/pulls - new
commit ( Separate code logic and other
<https://github.com/andreiversilov/WatirProject_AC/pull/2/commits/3b0e77abaef36c397c3290eab8ed57ecffe8b2d9>
 )

ср, 30 сент. 2020 г. в 10:47, Stepan Danci <notifications@github.com>:

**Comment by Stepandanci** [comment]
Please, refactor spec.
You need to save 2 html files `accounts.html` and `transactions.html`
and cover with spec methods `parse_accounts` and `parse_transactions`

You should show in spec:
1) Count of accounts `expect(accounts.count).to eq(5)`
2) Count of transactions `expect(transactions.count).to eq(10)`
3) Example of **one** account in hash foramt (check again example)
```ruby
  expect(accounts.first.to_hash).to eq(
    {
      "name"         => "Demo Everyday Account",
      "currency"     => "USD",
      "balance"      => 1959.90,
      "nature"       => "account",
      "transactions" => []
    }
  )
```
4) Example of **one** transaction in hash format (check my example).

```ruby
expect(transactions.first.to_hash).to eq(
  {
    "date": "2020-10-07",
    "description": "bought food",
    "amount": -89.31,
    "currency": "USD",
    "account_name": "Demo Everyday Account"
  }
)
```

**Comment by andreiversilov** [comment]
Hello Stepan.
The specs are fixed. The program did not need the file "transactions.html"
because everything was read from the fragment. But for specs, I added it.
With respect, Andrei.

https://github.com/andreiversilov/WatirProject_AC/pull/2/commits

ср, 7 окт. 2020 г. в 11:21, Stepan Danci <notifications@github.com>:

**Comment by Stepandanci** [comment]
As discussed with other developers, provide update.

- Do not store `html` as text in a file, but using `Nokogiri` extract it directly from the page and parse everything on the go
- Read `Ruby Style Guide` and update the naming of your variables. e.g. in Ruby we don't name a variable with `stringOftr` but instead he can use something like `tr_string`
- Read about Ruby iterators and replace the code which iterates based on indexes and calculations with easy and comfortable iterators. Also make sure to use with_index method instead of using an instance variable `@count`
- Separate `fetch_accounts` from `fetch_transactions` to have a clear sequence of methods

**Comment by andreiversilov** [comment]
Hello Stepan.
 I have updated the code as required.
https://github.com/andreiversilov/WatirProject_AC/pull/2/commits
With all respect, Andrei.

чт, 8 окт. 2020 г. в 12:24, Stepan Danci <notifications@github.com>:

**Comment by Stepandanci** [comment]
Your test task completed
